server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plazoleta_plazoleta
    username: postgres
    password: Induccion2025+

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Plazoleta Plazoleta"
appVersion: "1.0.0"

usuarios:
  url: http://localhost:8081/api/v1/usuarios